CATEGORY_TAGS = {
    "carne": ["protein", "gym", "non_vegan"],
    "paine": ["carb", "basic", "daily"],
    "lactate": ["healthy", "vegetarian", "dairy"],
    "lactate slabe": ["healthy", "low_fat", "vegetarian"],
    "legume": ["healthy", "vegan", "bio", "low_calorie"],
    "fructe": ["healthy", "vegan", "bio", "natural_sugar"],
    "dulciuri": ["unhealthy", "sweets", "treat"],
    "bere": ["alcohol", "unhealthy", "party"],
    "vin": ["alcohol", "gourmet", "dinner"],
    "chips-uri": ["unhealthy", "snack", "salty"],
    "suplimente proteice": ["gym", "supplement", "healthy", "functional_food"],
    "peste": ["healthy", "protein", "bio", "omega3"],
    "ready-to-eat": ["convenience", "ready_to_eat", "microwave"],
    "ciocolata": ["unhealthy", "sweets", "premium"],
    "biscuiti": ["unhealthy", "sweets", "snack"],
    "mancare gata": ["convenience", "ready_to_eat", "easy"],
    "fast-food": ["unhealthy", "ready_to_eat", "quick"],
    "tofu": ["vegan", "vegetarian", "healthy", "protein", "bio"],
    "seminte": ["vegan", "healthy", "snack", "bio", "fiber"],
    "smoothie": ["healthy", "vegan", "bio", "sweets", "drink"],
    "shake proteic": ["gym", "supplement", "healthy", "protein", "on_the_go"],
    "carne slaba": ["protein", "gym", "healthy", "low_fat"],
    "condimente": ["gourmet", "cooking", "natural"],
    "bauturi calde": ["coffee", "tea", "caffeine"],
    "bauturi racoritoare": ["drink", "cold", "sugar"],
    "nuci": ["snack", "healthy", "vegan", "bio"],
    "oua": ["protein", "vegetarian", "bio"],
    "patiserie": ["snack", "unhealthy", "breakfast"],
    "spread-uri": ["sweet", "savory", "snack"],
    "cereale": ["fiber", "breakfast", "healthy"],
    "ulei": ["cooking", "bio", "gourmet"],
    "miere": ["sweet", "healthy", "bio"],
    "conserve": ["ready_to_eat", "convenience", "protein"],
    "lactate vegetale": ["vegan", "dairy_free", "healthy"],
    "orez": ["carb", "bio", "cooking"],
    "condimente": ["spices", "gourmet", "flavor"],
    "fructe congelate": ["healthy", "convenience", "frozen"],
    "fructe uscate": ["snack", "healthy", "bio", "fiber"]
}
